Repository team-abcdedu/abcdedu-frontend, pull requests merged in 2024-12, with the labels that each got.

#273 refactor: 등업 게시판 제거
  public/sitemap.xml
  src/constants/navItems.ts
  src/pages/Community/Board.tsx
  src/pages/Community/components/Contents.tsx
  src/pages/Community/components/LevelUpButton.tsx
  src/pages/Community/components/Post.tsx
  src/pages/Community/constants/communityInfo.ts
  src/pages/Community/hooks/useGetPosts.ts
  src/pages/Community/hooks/useLevelUpMutation.ts
Labels: refactor, fix

#274 test: 클래스 커스텀훅 테스트 코드
  src/hooks/class/useClassDataByParams.test.ts
  src/hooks/class/useSubClassFileHandler.test.ts
  src/hooks/class/useSubClassFileHandler.ts
Labels: test, fix

#277 fix: 게시글 내용 조회 줄바꿈 처리
  src/pages/Community/components/PostSection.tsx
Labels: fix

#278 feat: 이전글 다음글 바로가기 추가
  src/pages/Community/components/Post.tsx
  src/pages/Community/components/PostNavigation.tsx
  src/types/community.ts
Labels: feature

#279 feat: 댓글 파일 첨부 구현
  src/hooks/class/useSubClassFileHandler.ts
  src/libs/compressor.ts
  src/pages/Community/components/CommentCard.tsx
  src/pages/Community/components/CommentForm.tsx
  src/pages/Community/components/PostNavigation.tsx
  src/pages/Community/hooks/useCommentForm.ts
  src/pages/Community/hooks/useCommentMutation.ts
  src/pages/Community/hooks/usePostForm.ts
  src/services/community.ts
  src/types/community.ts
  src/utils/getFileName.ts
Labels: feature, fix

#270 deploy: 24-12-11 운영 서버 배포
  public/sitemap.xml
  src/components/Pagination.test.tsx
  src/components/Pagination.tsx
  src/constants/navItems.ts
  src/hooks/class/useClassDataByParams.test.ts
  src/hooks/class/useClassDataByParams.ts
  src/hooks/class/useSubClassFileHandler.test.ts
  src/hooks/class/useSubClassFileHandler.ts
  src/hooks/class/useSubClassFileInfoList.ts
  src/hooks/survey/useGetSurvey.ts
  src/hooks/survey/useSurvey.ts
  src/hooks/survey/useSurveyList.ts
  src/libs/compressor.ts
  src/pages/Admin/Class/components/FileItem.tsx
  src/pages/Admin/Class/components/FileList.tsx
  src/pages/Admin/Class/components/FileUpdateModal.tsx
  src/pages/Admin/Class/components/FileUploadModal.tsx
  src/pages/Admin/Class/components/SubClassCard.tsx
  src/pages/Admin/Class/hooks/useFileUpdateMutation.ts
  src/pages/Admin/Class/hooks/useFileUploadMutation.ts
  src/pages/Admin/Contact/components/ContactDetailModal.test.tsx
  src/pages/Admin/Contact/index.test.tsx
  src/pages/Admin/Survey/components/SurveyDetailModal.tsx
  src/pages/Admin/Survey/components/SurveyRepliesViewModal.tsx
  src/pages/Admin/Survey/components/SurveyTable.tsx
  src/pages/Admin/Survey/hooks/useSurveyReplies.ts
  src/pages/Admin/constants/index.ts
  src/pages/Admin/types/index.ts
  src/pages/Community/Board.tsx
  src/pages/Community/components/CommentCard.tsx
  src/pages/Community/components/CommentForm.tsx
  src/pages/Community/components/Comments.tsx
  src/pages/Community/components/Contents.tsx
  src/pages/Community/components/LevelUpButton.tsx
  src/pages/Community/components/Post.tsx
  src/pages/Community/components/PostNavigation.tsx
  src/pages/Community/components/PostSection.tsx
  src/pages/Community/constants/communityInfo.ts
  src/pages/Community/hooks/useCommentForm.ts
  src/pages/Community/hooks/useCommentMutation.ts
  src/pages/Community/hooks/useGetPosts.ts
  src/pages/Community/hooks/useLevelUpMutation.ts
  src/pages/Community/hooks/usePostForm.ts
  src/pages/Contact/components/ContactModal.test.tsx
  src/pages/Contact/components/ContactModal.tsx
  src/pages/Contact/index.test.tsx
  src/pages/Survey/components/SurveyForm.tsx
  src/pages/Survey/components/SurveyFormBody.tsx
  src/pages/Survey/components/SurveyInfoSection.tsx
  src/pages/Survey/components/SurveyLayout.tsx
  src/pages/Survey/hooks/useSurveyForm.ts
  src/pages/Survey/hooks/useSurveyMutation.ts
  src/pages/Survey/index.tsx
  src/services/admin/class.ts
  src/services/admin/survey.ts
  src/services/class.ts
  src/services/community.ts
  src/types/community.ts
  src/types/survey.ts
  src/utils/getFileName.ts
Labels: deploy
