Repository team-abcdedu/abcdedu-frontend, pull requests merged in 2024-09, with the labels that each got.

#59 커뮤니티: 프로젝트,QnA,자유게시판 퍼블리싱
  src/pages/Community/Board.tsx
  src/pages/Community/LevelUp.tsx
  src/pages/Community/Project.tsx
  src/pages/Community/Qna.tsx
  src/pages/Community/components/PostData.tsx
  src/pages/Community/types/PostData.ts
  src/routes/PublicRoutes.tsx
Labels: feature

#61 feat: 문의 페이지 퍼블리싱
  src/assets/icons/envelope-o.svg
  src/assets/icons/inbox.svg
  src/constants/navItems.ts
  src/pages/contact/components/ContactModal.tsx
  src/pages/contact/constants/index.ts
  src/pages/contact/hooks/useContactForm.ts
  src/pages/contact/index.tsx
  src/pages/contact/types/index.ts
  src/routes/PublicRoutes.tsx
  src/styles/global.css
Labels: feature

#62 feat: 인증 관리 (1차)
  src/App.tsx
  src/components/Header/AuthModal/Login.tsx
  src/components/Header/HeaderButtons.tsx
  src/components/PrivateRoute.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useLoginForm.ts
  src/hooks/auth/useLogout.ts
  src/libs/api.ts
  src/services/auth.ts
  src/services/user.ts
  src/stores/.gitkeep
  src/stores/authSlice.ts
  src/stores/index.ts
  src/stores/userSlice.ts
  src/types/auth.ts
  src/types/user.ts
Labels: feature

#64 클래스 페이지 - 과제, 설문 퍼블리싱
  src/assets/icons/text-box-check.svg
  src/pages/Classes/[courseId]/[classCode]/index.tsx
  src/pages/Classes/components/AssignmentForm.tsx
  src/pages/Classes/components/ClassContent.tsx
  src/pages/Classes/components/ExamForm.tsx
  src/pages/Classes/components/SurveyForm.tsx
  src/pages/Classes/constants/assignmentInfo.ts
  src/pages/Classes/constants/courseInfo.ts
  src/pages/Classes/constants/surveyInfo.ts
  src/types/classTypes.ts
Labels: feature

#66 관리자 페이지 퍼블리싱
  src/components/AdminLayout.tsx
  src/components/AdminRoute.tsx
  src/constants/navItems.ts
  src/mock/adminMock.ts
  src/pages/Admin/Assignment.tsx
  src/pages/Admin/Survey.tsx
  src/pages/Admin/constants/tableInfo.ts
  src/pages/Admin/index.tsx
  src/routes/AdminRoutes.tsx
Labels: feature

#67 feat: 문의 남기기 구현
  src/components/Header/MobileMenu.tsx
  src/components/Header/MobileNav.tsx
  src/components/Header/index.tsx
  src/pages/Contact/components/ContactModal.tsx
  src/pages/Contact/constants/index.ts
  src/pages/Contact/hooks/useContactForm.ts
  src/pages/Contact/index.tsx
  src/pages/Contact/types/index.ts
  src/pages/contact/hooks/useContactForm.ts
  src/routes/PublicRoutes.tsx
  src/services/contact.ts
  src/types/contact.ts
Labels: feature

#70 feat: 회원 프로필 조회 및 수정 구현
  package-lock.json
  package.json
  src/components/Header/HeaderButtons.tsx
  src/components/Skeleton.tsx
  src/libs/api.ts
  src/libs/compressor.ts
  src/pages/My/components/EditAccount.tsx
  src/pages/My/components/EditModal.tsx
  src/pages/My/components/EditProfile.tsx
  src/pages/My/components/ProfileLoading.tsx
  src/pages/My/hooks/useAccountForm.ts
  src/pages/My/hooks/useGetProfile.ts
  src/pages/My/hooks/useProfileForm.ts
  src/pages/My/hooks/useProfileMutation.ts
  src/pages/My/index.tsx
  src/pages/My/types/index.ts
  src/services/user.ts
  src/types/user.ts
  src/utils/convertURLtoFile.ts
  tailwind.config.js
Labels: feature

#72 과제, 설문 페이지 분리
  src/assets/icons/check-circle.svg
  src/assets/icons/exclamation-mark.svg
  src/components/Header/HeaderButtons.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Header/MobileMenu.tsx
  src/components/Header/index.tsx
  src/components/Layout.tsx
  src/components/MessageModal.tsx
  src/constants/navItems.ts
  src/hooks/useClassForm.ts
  src/pages/Assignment/components/AssignmentForm.tsx
  src/pages/Assignment/constants/index.ts
  src/pages/Assignment/index.tsx
  src/pages/Assignment/types/index.ts
  src/pages/Classes/[classId]/[subClassId]/index.tsx
  src/pages/Classes/[classId]/index.tsx
  src/pages/Classes/[courseId]/[classCode]/index.tsx
  src/pages/Classes/[courseId]/index.tsx
  src/pages/Classes/components/AssignmentForm.tsx
  src/pages/Classes/components/ClassContent.tsx
  src/pages/Classes/components/ClassList.tsx
  src/pages/Classes/components/ClassOverview.tsx
  src/pages/Classes/components/CourseOverview.tsx
  src/pages/Classes/components/ExamForm.tsx
  src/pages/Classes/components/Hero.tsx
  src/pages/Classes/components/MediaContents.tsx
  src/pages/Classes/components/SubClassContent.tsx
  src/pages/Classes/components/SubClassNavigationCard.tsx
  src/pages/Classes/components/SubClassNavigationCardGroup.tsx
  src/pages/Classes/components/SubClassOverview.tsx
  src/pages/Classes/components/SurveyForm.tsx
  src/pages/Classes/constants/imgUrl.ts
  src/pages/Classes/constants/index.ts
  src/pages/Classes/constants/surveyInfo.ts
  src/pages/Classes/index.tsx
  src/pages/Classes/types/index.ts
  src/pages/Survey/components/SurveyForm.tsx
  src/pages/Survey/components/SurveyItem.tsx
  src/pages/Survey/constants/index.ts
  src/pages/Survey/index.tsx
  src/pages/Survey/types/index.ts
  src/routes/PublicRoutes.tsx
  src/services/class.ts
  src/types/classForm.ts
  src/types/classTypes.ts
Labels: feature

#74 feat: 회사 소개 퍼블리싱
  package-lock.json
  package.json
  src/components/Layout.tsx
  src/constants/navItems.ts
  src/pages/AboutUs/Gallery.tsx
  src/pages/AboutUs/History.tsx
  src/pages/AboutUs/components/ImageModal.tsx
  src/pages/AboutUs/components/MobileLinks.tsx
  src/pages/AboutUs/components/TeamInfo.tsx
  src/pages/AboutUs/constants/index.ts
  src/pages/AboutUs/index.tsx
  src/pages/AboutUs/types/index.ts
  src/routes/PublicRoutes.tsx
  src/styles/global.css
Labels: feature

#73 관리자 클래스 관리 페이지 퍼블리싱
  src/components/AdminLayout.tsx
  src/mock/adminMock.ts
  src/pages/Admin/Assignment.tsx
  src/pages/Admin/Class.tsx
  src/pages/Admin/Survey.tsx
  src/pages/Admin/components/ClassRegisterModal.tsx
  src/pages/Admin/components/SubClassRegisterModal.tsx
  src/pages/Admin/constants/index.ts
  src/pages/Admin/constants/tableInfo.ts
  src/pages/Admin/hooks/useClassRegisterForm.ts
  src/pages/Admin/hooks/useSubClassRegisterForm.ts
  src/pages/Admin/types/index.ts
  src/routes/AdminRoutes.tsx
  src/services/admin/class.ts
Labels: feature

#77 관리자 페이지 퍼블리싱(과제, 설문, 이론)
  src/components/AdminLayout.tsx
  src/pages/Admin/Assignment.tsx
  src/pages/Admin/Class.tsx
  src/pages/Admin/Survey.tsx
  src/pages/Admin/Theory.tsx
  src/pages/Admin/components/AssignmentDetailModal.tsx
  src/pages/Admin/components/ClassDetailModal.tsx
  src/pages/Admin/components/ClassRegisterModal.tsx
  src/pages/Admin/components/DetailModalHeader.tsx
  src/pages/Admin/components/SubClassRegisterModal.tsx
  src/pages/Admin/components/SurveyDetailModal.tsx
  src/pages/Admin/constants/index.ts
  src/pages/Admin/types/index.ts
  src/routes/AdminRoutes.tsx
Labels: feature

#78 등업 시키기 기능 퍼블리싱
  src/pages/Community/LevelUp.tsx
  src/pages/Community/components/Hero.tsx
  src/pages/Community/components/PostData.tsx
  src/pages/Community/types/PostData.ts
Labels: feature

#79 feat: 인증 관리 2차
  package-lock.json
  package.json
  src/components/Header/HeaderButtons.tsx
  src/config/index.ts
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useLogout.ts
  src/libs/api.ts
  src/services/auth.ts
  src/stores/authSlice.ts
  src/stores/index.ts
  vite.config.ts
Labels: bug, feature

#81 refactor: 문의 작성 api 변경 사항 적용 및 메인 페이지 커리큘럼 수정
  src/constants/navItems.ts
  src/pages/Home/components/Curriculum.tsx
  src/pages/Home/constants/index.ts
  src/services/contact.ts
Labels: refactor

#84 관리자 클래스 기능
  src/components/AdminRoute.tsx
  src/components/Header/HeaderNav.tsx
  src/components/Header/MobileNav.tsx
  src/constants/navItems.ts
  src/pages/Admin/Class.tsx
  src/pages/Admin/components/ClassDetailModal.tsx
  src/pages/Admin/components/ClassRegisterModal.tsx
  src/pages/Admin/components/SubClassRegisterModal.tsx
  src/pages/Admin/constants/index.ts
  src/pages/Admin/hooks/useClass.ts
  src/pages/Admin/hooks/useClassRegisterForm.ts
  src/pages/Admin/hooks/useSubClassRegisterForm.ts
  src/pages/Admin/types/index.ts
  src/services/admin/class.ts
Labels: feature

#86 헤더 css 수정
  src/components/Header/HeaderButtons.tsx
  src/components/Header/HeaderNav.tsx
Labels: bug

#88 관리자 페이지 폴더 구조 개선
  src/pages/Admin/Assignment/components/AssignmentDetailModal.tsx
  src/pages/Admin/Assignment/components/AssignmentTable.tsx
  src/pages/Admin/Assignment/index.tsx
  src/pages/Admin/Class/components/ClassDetailModal.tsx
  src/pages/Admin/Class/components/ClassRegisterModal.tsx
  src/pages/Admin/Class/components/DataItem.tsx
  src/pages/Admin/Class/components/SubClassRegisterModal.tsx
  src/pages/Admin/Class/hooks/useClass.ts
  src/pages/Admin/Class/hooks/useClassRegisterForm.ts
  src/pages/Admin/Class/hooks/useSubClassRegisterForm.ts
  src/pages/Admin/Class/index.tsx
  src/pages/Admin/Exam/components/ExamRegisterModal.tsx
  src/pages/Admin/Exam/index.tsx
  src/pages/Admin/Survey/components/SurveyDetailModal.tsx
  src/pages/Admin/Survey/components/SurveyTable.tsx
  src/pages/Admin/Survey/index.tsx
  src/pages/Admin/Theory/components/TheoryRegisterModal.tsx
  src/pages/Admin/Theory/index.tsx
  src/pages/Admin/components/FormBuilder/QuestionnaireBuilder.tsx
  src/pages/Admin/components/FormBuilder/QuestionnaireInput.tsx
  src/pages/Admin/components/FormBuilder/index.tsx
Labels: refactor

#90 fix: 개발 환경에서만 proxy 적용하도록 수정
  src/config/index.ts
  vite.config.ts
Labels: bug

#93 refactor: 메인 페이지 수정 사항 반영
  src/pages/Home/components/AboutUs.tsx
  src/pages/Home/constants/index.ts
Labels: refactor, fix

#95 fix: interceptor 수정
  src/libs/api.ts
Labels: bug, fix

#91 feat: 관리자 문의 조회 구현
  src/components/AdminLayout.tsx
  src/pages/Admin/Contact/components/ContactDetailLoading.tsx
  src/pages/Admin/Contact/components/ContactDetailModal.tsx
  src/pages/Admin/Contact/hooks/useGetContact.ts
  src/pages/Admin/Contact/hooks/useGetContactList.ts
  src/pages/Admin/Contact/index.tsx
  src/pages/Admin/constants/index.ts
  src/pages/Admin/types/index.ts
  src/routes/AdminRoutes.tsx
  src/services/contact.ts
  src/types/contact.ts
Labels: feature

#98 메뉴에서 커뮤니티 - 과제제출 삭제
  src/constants/navItems.ts
  src/routes/PublicRoutes.tsx
Labels: fix

#104 refactor: router lazy 적용
  src/components/AdminLayout.tsx
  src/components/Layout.tsx
  src/routes/AdminRoutes.tsx
  src/routes/PrivateRoutes.tsx
  src/routes/PublicRoutes.tsx
Labels: refactor

#106 feat: 페이징 공통 부분 구현 및 관리자 문의 목록 페이징 처리 추가
  src/components/Pagination.tsx
  src/pages/Admin/Contact/components/ContactDetailModal.tsx
  src/pages/Admin/Contact/hooks/useGetContactList.ts
  src/pages/Admin/Contact/index.tsx
  src/services/contact.ts
  src/types/index.ts
Labels: feature, refactor

#101 관리자 클래스 기능, 유저 시험 퍼블리싱
  src/hooks/class/useGetClass.ts
  src/hooks/class/useGetSubClassAnswerFile.ts
  src/hooks/class/useGetSubClassFile.ts
  src/hooks/class/useGetSubClassFileList.ts
  src/pages/Admin/Class/components/ClassDetail.tsx
  src/pages/Admin/Class/components/ClassDetailModal.tsx
  src/pages/Admin/Class/components/ClassRegisterModal.tsx
  src/pages/Admin/Class/components/ClassTable.tsx
  src/pages/Admin/Class/components/DataItem.tsx
  src/pages/Admin/Class/components/FileItem.tsx
  src/pages/Admin/Class/components/FileList.tsx
  src/pages/Admin/Class/components/FileUploadModal.tsx
  src/pages/Admin/Class/components/StudentFileUploadModal.tsx
  src/pages/Admin/Class/components/SubClassCard.tsx
  src/pages/Admin/Class/components/SubClassRegisterModal.tsx
  src/pages/Admin/Class/hooks/useClass.ts
  src/pages/Admin/Class/hooks/useClassRegisterForm.ts
  src/pages/Admin/Class/hooks/useFileUpload.ts
  src/pages/Admin/Class/hooks/useStudentFileUpload.ts
  src/pages/Admin/Class/hooks/useSubClassRegisterForm.ts
  src/pages/Admin/Class/index.tsx
  src/pages/Admin/types/index.ts
  src/pages/Classes/components/SubClassContent.tsx
  src/pages/Classes/components/SubClassNavigationCard.tsx
  src/pages/Classes/constants/index.ts
  src/pages/Classes/types/index.ts
  src/services/admin/class.ts
  src/services/class.ts
  src/types/class.ts
Labels: feature

#105 과제 기능 구현
  src/constants/navItems.ts
  src/pages/Assignment/components/AssignmentForm.tsx
  src/pages/Assignment/constants/index.ts
  src/pages/Assignment/index.tsx
  src/pages/Assignment/types/index.ts
  src/pages/Homework/components/HomeworkForm.tsx
  src/pages/Homework/components/UserInput.tsx
  src/pages/Homework/constants/index.ts
  src/pages/Homework/hooks/useGetHomework.ts
  src/pages/Homework/hooks/useGetHomeworks.ts
  src/pages/Homework/hooks/useGetMyHomework.ts
  src/pages/Homework/hooks/useHomeworkForm.ts
  src/pages/Homework/index.tsx
  src/routes/PublicRoutes.tsx
  src/services/homework.ts
  src/types/homework.ts
Labels: feature

#110 refactor: 메인, 회사 소개, 문의, 프로필 페이지 성능 개선
  src/assets/icons/clock.png
  src/assets/icons/clock.webp
  src/assets/icons/school.png
  src/assets/icons/school.webp
  src/assets/icons/students.png
  src/assets/icons/students.webp
  src/assets/images/handshake.png
  src/assets/images/handshake.webp
  src/components/Footer/FooterSns.tsx
  src/components/Header/index.tsx
  src/constants/snsItems.tsx
  src/pages/AboutUs/Gallery.tsx
  src/pages/AboutUs/History.tsx
  src/pages/AboutUs/components/TeamInfo.tsx
  src/pages/AboutUs/index.tsx
  src/pages/Contact/index.tsx
  src/pages/Home/components/AboutUs.tsx
  src/pages/Home/components/Achievements.tsx
  src/pages/Home/constants/index.ts
  src/pages/My/index.tsx
Labels: refactor

#111 feat: Class 페이지 api 연결
  src/assets/icons/paperclip.svg
  src/components/ClassLayout/SubClassNavigationCard.tsx
  src/components/ClassLayout/SubClassNavigationCardGroup.tsx
  src/components/ClassLayout/SubClassOverview.tsx
  src/components/ClassLayout/index.tsx
  src/hooks/class/useGetSubClassFile.ts
  src/hooks/class/useGetSubClassFileList.ts
  src/hooks/class/useGetSubClassGeneralFile.ts
  src/hooks/class/useGetSubClassIdMap.ts
  src/hooks/class/useGetSubClassStudentFile.ts
  src/pages/Admin/Class/components/ClassDetail.tsx
  src/pages/Admin/Class/components/ClassTable.tsx
  src/pages/Admin/Class/components/FileItem.tsx
  src/pages/Admin/constants/index.ts
  src/pages/Admin/types/index.ts
  src/pages/Classes/[classId]/[subClassId]/index.tsx
  src/pages/Classes/[classId]/index.tsx
  src/pages/Classes/components/ClassList.tsx
  src/pages/Classes/components/ClassOverview.tsx
  src/pages/Classes/components/ExamContent.tsx
  src/pages/Classes/components/SubClassContent.tsx
  src/pages/Classes/components/SubClassOverview.tsx
  src/pages/Classes/constants/index.ts
  src/pages/Classes/hooks/useFileHandler.ts
  src/pages/Classes/index.tsx
  src/pages/Classes/types/index.ts
  src/routes/PublicRoutes.tsx
  src/services/class.ts
  src/types/class.ts
Labels: feature

#114 feat: 관리자 과제 등록 api 연결
  src/components/AdminLayout.tsx
  src/hooks/homework/useGetHomework.ts
  src/hooks/homework/useGetHomeworkList.ts
  src/pages/Admin/Assignment/components/AssignmentDetailModal.tsx
  src/pages/Admin/Assignment/components/AssignmentTable.tsx
  src/pages/Admin/Assignment/index.tsx
  src/pages/Admin/Exam/components/ExamRegisterModal.tsx
  src/pages/Admin/Exam/index.tsx
  src/pages/Admin/Homework/components/HomeworkList.tsx
  src/pages/Admin/Homework/hooks/useSubmitHomeworkForm.ts
  src/pages/Admin/Homework/index.tsx
  src/pages/Admin/Survey/index.tsx
  src/pages/Admin/Theory/components/TheoryRegisterModal.tsx
  src/pages/Admin/Theory/index.tsx
  src/pages/Admin/components/FormBuilder/QuestionnaireBuilder.tsx
  src/pages/Admin/components/FormBuilder/QuestionnaireInput.tsx
  src/pages/Admin/components/FormBuilder/RequiredField.tsx
  src/pages/Admin/components/FormBuilder/index.tsx
  src/pages/Admin/constants/form.ts
  src/pages/Admin/constants/index.ts
  src/pages/Admin/types/index.ts
  src/pages/Homework/hooks/useGetHomeworks.ts
  src/routes/AdminRoutes.tsx
  src/services/admin/homework.ts
  src/services/homework.ts
  src/types/homework.ts
Labels: feature

#115 refactor: 커뮤니티 게시판 리팩토링
  src/constants/navItems.ts
  src/mock/Comment.tsx
  src/mock/Community.tsx
  src/pages/Community/Board.tsx
  src/pages/Community/LevelUp.tsx
  src/pages/Community/PostDetail.tsx
  src/pages/Community/Project.tsx
  src/pages/Community/Qna.tsx
  src/pages/Community/Submit.tsx
  src/pages/Community/components/Comments.tsx
  src/pages/Community/components/CommunityInfo.tsx
  src/pages/Community/components/Contents.tsx
  src/pages/Community/components/LevelUpButton.tsx
  src/pages/Community/components/List.tsx
  src/pages/Community/components/PostActions.tsx
  src/pages/Community/components/PostData.tsx
  src/pages/Community/components/PostFormModal.tsx
  src/pages/Community/components/WirtePostModal.tsx
  src/pages/Community/constants/communityInfo.ts
  src/pages/Community/hooks/usePostForm.ts
  src/pages/Community/index.tsx
  src/pages/Community/types/Comment.ts
  src/pages/Community/types/PostData.ts
  src/pages/Community/types/WriteModal.ts
  src/pages/Community/types/index.ts
  src/routes/PublicRoutes.tsx
  src/services/community.ts
  src/styles/global.css
  src/types/community.ts
Labels: refactor

#119 refactor: 게시글 댓글 리팩토링
  src/mock/Comment.tsx
  src/pages/Community/Board.tsx
  src/pages/Community/PostDetail.tsx
  src/pages/Community/components/CommentCard.tsx
  src/pages/Community/components/CommentForm.tsx
  src/pages/Community/components/Comments.tsx
  src/pages/Community/components/Contents.tsx
  src/pages/Community/components/MoreButton.tsx
  src/pages/Community/types/Comment.ts
Labels: feature, refactor

#120 bug: 모바일 메뉴에서 버튼 클릭 시 메뉴 닫히도록 수정
  src/components/Header/HeaderButtons.tsx
  src/components/Header/MobileMenu.tsx
  src/components/Header/MobileNav.tsx
Labels: bug, fix

#122 refactor: 헤더 드롭다운 아이템 태그 수정
  src/components/Header/HeaderNav.tsx
Labels: refactor

#127 refactor: 관리자 탭 태그 수정
  src/components/AdminLayout.tsx
Labels: refactor

#129 feat: 404 페이지 추가
  src/pages/NotFound.tsx
  src/routes/PublicRoutes.tsx
Labels: feature

#126 feat: 클래스 파일 api 연결
  src/hooks/class/useGetSubClassStudentFile.ts
  src/pages/Admin/Class/components/ClassDetail.tsx
  src/pages/Admin/Class/components/FileActionButtons.tsx
  src/pages/Admin/Class/components/FileItem.tsx
  src/pages/Admin/Class/components/FileItemModal.tsx
  src/pages/Admin/Class/components/GeneralFileUploadModal.tsx
  src/pages/Admin/Class/components/StudentFileUploadModal.tsx
  src/pages/Admin/Class/components/SubClassCard.tsx
  src/pages/Admin/Class/hooks/useGeneralFileUpdate.ts
  src/pages/Admin/Class/hooks/useGeneralFileUpload.ts
  src/pages/Admin/Class/hooks/useStudentFileUpdate.ts
  src/pages/Classes/[classId]/[subClassId]/index.tsx
  src/pages/Classes/components/ClassOverview.tsx
  src/pages/Classes/components/ExamContent.tsx
  src/services/admin/class.ts
  src/services/class.ts
Labels: feature

#128 feat: 게시판 CRUD 구현
  src/mock/Community.tsx
  src/pages/Community/Board.tsx
  src/pages/Community/PostDetail.tsx
  src/pages/Community/components/AccessError.tsx
  src/pages/Community/components/List.tsx
  src/pages/Community/components/PostFormModal.tsx
  src/pages/Community/components/PostSection.tsx
  src/pages/Community/hooks/useGetPost.ts
  src/pages/Community/hooks/useGetPosts.ts
  src/pages/Community/hooks/usePostForm.ts
  src/pages/Community/hooks/usePostMutation.ts
  src/services/community.ts
  src/types/community.ts
  src/utils/getFileName.ts
Labels: feature

#133 feat: 등업시키기 구현
  src/pages/Community/Board.tsx
  src/pages/Community/PostDetail.tsx
  src/pages/Community/components/LevelUpButton.tsx
  src/pages/Community/hooks/useLevelUpMutation.ts
  src/services/user.ts
Labels: feature

#134 feat: 댓글 CRUD 구현
  src/components/Pagination.tsx
  src/mock/Comment.tsx
  src/pages/Community/PostDetail.tsx
  src/pages/Community/components/CommentCard.tsx
  src/pages/Community/components/CommentForm.tsx
  src/pages/Community/components/Comments.tsx
  src/pages/Community/hooks/useCommentMutation.ts
  src/pages/Community/hooks/useGetComments.ts
  src/services/community.ts
  src/types/community.ts
Labels: feature

#138 fix: 게시글 수정 오류 해결
  src/components/AccessError.tsx
  src/pages/Community/PostDetail.tsx
  src/pages/Community/components/AccessError.tsx
  src/pages/Community/components/PostFormModal.tsx
  src/pages/Community/hooks/usePostForm.ts
  src/services/community.ts
  src/utils/isEndWithConsonant.ts
Labels: refactor, fix

#142 fix: 게시글, 댓글 검증
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useLogout.ts
  src/pages/Community/PostDetail.tsx
  src/pages/Community/components/CommentCard.tsx
  src/pages/Community/components/Comments.tsx
  src/pages/Community/components/PostSection.tsx
  src/pages/Community/hooks/useGetPost.ts
  src/services/user.ts
  src/types/user.ts
Labels: refactor, fix

#143 feat: 로그아웃 시 쿼리 캐시 제거
  src/hooks/auth/useLogout.ts
  src/hooks/homework/useGetHomeworkList.ts
  src/hooks/survey/useGetSurveyList.ts
  src/libs/api.ts
  src/libs/react-query.ts
Labels: feature, refactor

#144 fix: 게시글 파일 삭제 예외 처리 추가 및 로직 수정 #132
  src/pages/Community/hooks/usePostForm.ts
Labels: bug, fix

#145 fix: 관리자 파일 관리 수정
  src/hooks/class/useGetSubClassFileList.ts
  src/hooks/class/useGetSubClassGeneralFile.ts
  src/hooks/class/useGetSubClassStudentFile.ts
  src/pages/Admin/Class/components/ClassDetail.tsx
  src/pages/Admin/Class/components/FileActionButtons.tsx
  src/pages/Admin/Class/components/FileItem.tsx
  src/pages/Admin/Class/components/FileItemDetails.tsx
  src/pages/Admin/Class/components/FileItemModal.tsx
  src/pages/Admin/Class/components/FileList.tsx
  src/pages/Admin/Class/components/GeneralFileItem.tsx
  src/pages/Admin/Class/components/GeneralFileUploadModal.tsx
  src/pages/Admin/Class/components/StudentFileItem.tsx
  src/pages/Admin/Class/components/StudentFileUploadModal.tsx
  src/pages/Admin/Class/components/SubClassCard.tsx
  src/pages/Admin/Class/hooks/useGeneralFileUpdate.ts
  src/pages/Admin/Class/hooks/useGeneralFileUpload.ts
  src/pages/Admin/Class/hooks/useStudentFileUpdate.ts
  src/pages/Admin/Class/hooks/useStudentFileUpload.ts
  src/pages/Classes/[classId]/[subClassId]/index.tsx
  src/pages/Classes/hooks/useFileHandler.ts
  src/pages/Classes/types/index.ts
Labels: refactor, fix

#148 feat: Loader 컴포넌트 추가
  package-lock.json
  package.json
  src/components/Loader.tsx
  src/pages/Community/components/MoreButton.tsx
  tailwind.config.js
Labels: feature

#147 fix: 서브클래스 아이콘 조건부 렌더링 추가
  src/pages/Classes/[classId]/[subClassId]/index.tsx
  src/pages/Classes/components/ExamContent.tsx
  src/pages/Classes/hooks/useFileHandler.ts
Labels: refactor, fix

#146 fix: 프로필 이미지 수정 오류 해결
  src/pages/My/components/EditProfile.tsx
  src/pages/My/hooks/useProfileForm.ts
  src/pages/My/index.tsx
  src/utils/convertURLtoFile.ts
Labels: bug, feature, fix

#151 fix: 제출용 파일 오류 수정
  src/hooks/class/useGetSubClassStudentFile.ts
  src/pages/Admin/Class/components/ClassTable.tsx
  src/pages/Admin/Class/components/FileItemDetails.tsx
  src/pages/Admin/Class/components/FileList.tsx
  src/pages/Admin/Class/components/GeneralFileItem.tsx
  src/pages/Admin/Class/components/StudentFileItem.tsx
  src/pages/Admin/Class/components/SubClassCard.tsx
  src/pages/Admin/Class/hooks/useGeneralFileUpdate.ts
  src/pages/Admin/Class/hooks/useStudentFileUpdate.ts
  src/pages/Admin/Class/hooks/useStudentFileUpload.ts
  src/pages/Admin/Survey/components/SurveyTable.tsx
  src/pages/Classes/[classId]/[subClassId]/index.tsx
  src/pages/Classes/components/ExamContent.tsx
  src/services/class.ts
Labels: bug, fix

#152 fix: 파일 타입 수정
  src/pages/Admin/Class/components/GeneralFileItem.tsx
Labels: bug, fix

#156 fix: 설문 페이지 수정
  src/pages/Homework/[homeworkId]/index.tsx
  src/pages/Homework/components/HomeworkListTable.tsx
  src/pages/Homework/index.tsx
  src/pages/Survey/[surveyId]/index.tsx
  src/pages/Survey/components/SurveyListTable.tsx
  src/pages/Survey/index.tsx
  src/routes/PublicRoutes.tsx
Labels: refactor, fix

#157 fix: 이미지 height 수정
  src/pages/AboutUs/components/TeamInfo.tsx
  src/pages/Home/components/AboutUs.tsx
  src/pages/Home/components/Achievements.tsx
Labels: bug, fix

#159 feat: 클래스 영상 링크 추가
  src/pages/Classes/components/Hero.tsx
  src/pages/Classes/components/MediaContents.tsx
  src/pages/Classes/constants/index.ts
Labels: feature

#160 fix: 새싹 등급 게시글 첨부 파일 다운로드 못 하게 수정
  src/pages/Community/components/Comments.tsx
  src/pages/Community/components/PostSection.tsx
Labels: fix

#161 fix: class 페이지 문구 수정
  src/pages/Classes/components/ClassOverview.tsx
Labels: fix

#163 fix: 설문 페이지 오류 시 나오는 화면 수정
  src/components/AccessError.tsx
  src/pages/Survey/components/SurveyForm.tsx
Labels: bug, fix

#166 fix: 클래스 파일 타입, 다운로드 파일명 수정
  src/pages/Admin/Class/components/FileItemDetails.tsx
  src/pages/Admin/Class/components/GeneralFileItem.tsx
  src/pages/Classes/[classId]/[subClassId]/index.tsx
  src/pages/Classes/components/ExamContent.tsx
  src/pages/Classes/hooks/useFileHandler.ts
  src/pages/Classes/types/index.ts
Labels: bug, fix

#167 deploy: 24-09-21 운영 서버 배포(2)
  src/pages/Admin/Class/components/FileItemDetails.tsx
  src/pages/Admin/Class/components/GeneralFileItem.tsx
  src/pages/Classes/[classId]/[subClassId]/index.tsx
  src/pages/Classes/components/ExamContent.tsx
  src/pages/Classes/hooks/useFileHandler.ts
  src/pages/Classes/types/index.ts
Labels: deploy

#168 fix: a 태그 다운로드 속성 수정
  src/pages/Admin/Class/components/FileItemDetails.tsx
  src/pages/Classes/components/ExamContent.tsx
  src/pages/Classes/hooks/useFileHandler.ts
Labels: bug, fix

#169 deploy: 24-09-21 운영 서버 배포(3)
  src/pages/Admin/Class/components/FileItemDetails.tsx
  src/pages/Classes/components/ExamContent.tsx
  src/pages/Classes/hooks/useFileHandler.ts
Labels: deploy

#174 refactor: 과제, 설문 페이지 개선
  src/components/AccessError.tsx
  src/pages/Homework/components/HomeworkForm.tsx
  src/pages/Homework/components/HomeworkFormBody.tsx
  src/pages/Homework/components/HomeworkLoading.tsx
  src/pages/Survey/components/SurveyForm.tsx
  src/pages/Survey/components/SurveyFormBody.tsx
  src/pages/Survey/components/SurveyFormHeader.tsx
  src/pages/Survey/components/SurveyLoading.tsx
Labels: refactor, fix

#177 refactor: 이미지 크기 수정
  src/assets/icons/clock.webp
  src/assets/icons/logo.png
  src/assets/icons/naver band.png
  src/assets/icons/naver blog.jpg
  src/assets/icons/naver-band.png
  src/assets/icons/naver-blog.png
  src/assets/icons/react.svg
  src/assets/images/snu.png
  src/constants/snsItems.tsx
Labels: refactor

#176 refactor: Form 개선
  src/components/FormErrorMessage.tsx
  src/components/Header/AuthModal/Login.tsx
  src/components/Header/AuthModal/Register.tsx
  src/hooks/auth/useLoginForm.ts
  src/hooks/auth/useRegisterForm.ts
  src/pages/Community/components/PostFormModal.tsx
  src/pages/Community/hooks/usePostForm.ts
  src/pages/Contact/components/ContactModal.tsx
  src/pages/Contact/hooks/useContactForm.ts
  src/pages/My/components/EditProfile.tsx
  src/pages/My/hooks/useProfileForm.ts
  src/utils/convertURLtoFile.ts
Labels: feature, refactor

#180 refactor: 400번대 API 오류 예외 처리 개선
  src/components/AccessError.tsx
  src/hooks/auth/useLoginForm.ts
  src/hooks/auth/useRegisterForm.ts
  src/hooks/homework/useGetHomework.ts
  src/hooks/survey/useGetSurvey.ts
  src/hooks/survey/useGetSurveyList.ts
  src/libs/api.ts
  src/libs/errors.ts
  src/pages/Admin/Class/hooks/useClassRegisterForm.ts
  src/pages/Admin/Class/hooks/useSubClassRegisterForm.ts
  src/pages/Community/PostDetail.tsx
  src/pages/Community/hooks/useGetPost.ts
  src/pages/Community/hooks/usePostMutation.ts
  src/pages/Contact/hooks/useContactForm.ts
  src/pages/Homework/components/HomeworkForm.tsx
  src/pages/My/hooks/useProfileMutation.ts
  src/pages/Survey/components/SurveyForm.tsx
Labels: bug, refactor

#181 refactor: 게시글 목록, 상세 조회 개선
  public/favicon-16x16.png
  public/favicon-32x32.png
  src/components/Header/index.tsx
  src/components/Pagination.tsx
  src/pages/Admin/Contact/index.tsx
  src/pages/Community/components/Comments.tsx
  src/pages/Community/components/List.tsx
  src/pages/Community/components/MoreButton.tsx
  src/pages/Community/components/PostSection.tsx
  src/pages/Community/hooks/useGetComments.ts
  src/pages/Community/hooks/useGetPosts.ts
  src/services/community.ts
  src/types/community.ts
  src/utils/formatDate.ts
Labels: feature, refactor, fix

#184 build: dependabot alerts로 인한 vite 버전 업데이트
  package-lock.json
  package.json
Labels: dependencies

#189 fix: 시험파일 pdf 여부에 따라 버튼, viewer 조건부 렌더링 추가
  src/pages/Classes/components/ExamContent.tsx
Labels: refactor, fix

#190 deploy: 24-09-24 운영 서버 배포 (1)
  src/pages/Classes/components/ExamContent.tsx
  src/utils/convertURLtoFile.ts
Labels: deploy

#193 fix: 메인페이지 모바일 UI 수정, 게시글 및 댓글 한국 시간 적용
  src/pages/Community/components/CommentCard.tsx
  src/pages/Community/components/List.tsx
  src/pages/Community/components/PostSection.tsx
  src/pages/Home/components/AboutUs.tsx
  src/utils/formatDate.ts
Labels: fix

#195 fix: 클래스 파일 관련 문제 수정
  src/pages/Classes/[classId]/[subClassId]/index.tsx
  src/pages/Classes/components/ExamContent.tsx
  src/pages/Classes/components/SubClassFileItem.tsx
  src/pages/Classes/hooks/useGetPdfUrl.ts
  src/pages/My/hooks/useProfileForm.ts
  src/types/class.ts
  src/utils/convertURLtoFile.ts
Labels: bug, refactor

#197 fix: 클래스 이동 시 파일 상태 문제
  src/pages/Classes/[classId]/[subClassId]/index.tsx
Labels: bug

#198 fix: 시험 파일 버튼 문구 수정
  src/pages/Classes/components/ExamContent.tsx
Labels: fix

#199 deploy: 24-09-25 운영 서버 배포
  src/pages/Classes/[classId]/[subClassId]/index.tsx
  src/pages/Classes/components/ExamContent.tsx
  src/pages/Classes/components/SubClassFileItem.tsx
  src/pages/Classes/hooks/useGetPdfUrl.ts
  src/pages/Community/components/CommentCard.tsx
  src/pages/Community/components/List.tsx
  src/pages/Community/components/PostSection.tsx
  src/pages/Home/components/AboutUs.tsx
  src/pages/Homework/components/HomeworkForm.tsx
  src/pages/Homework/components/HomeworkFormBody.tsx
  src/pages/Homework/hooks/useHomeworkForm.ts
  src/pages/My/hooks/useProfileForm.ts
  src/pages/Survey/components/SurveyForm.tsx
  src/pages/Survey/components/SurveyFormBody.tsx
  src/pages/Survey/hooks/useSurveyForm.ts
  src/types/class.ts
  src/utils/convertURLtoFile.ts
  src/utils/formatDate.ts
Labels: deploy

#204 refactor: 헤더 모바일 메뉴 사이드바로 변경
  src/components/Footer/FooterNav.tsx
  src/components/Header/HeaderButtons.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Header/HeaderNav.tsx
  src/components/Header/MenuToggle.tsx
  src/components/Header/MobileMenu.tsx
  src/components/Header/MobileNav.tsx
  src/components/Header/MobileSidebar.tsx
  src/components/Header/index.tsx
  src/components/Layout.tsx
  src/constants/navItems.ts
  src/hooks/useMenuAnimation.ts
  src/stores/headerSlice.ts
  src/types/navTypes.ts
Labels: refactor, fix

#206 fix: store 구조분해할당 수정
  src/hooks/class/useGetSubClassGeneralFile.ts
  src/hooks/homework/useGetHomework.ts
  src/hooks/survey/useGetSurvey.ts
  src/hooks/useClassForm.ts
  src/pages/Classes/[classId]/[subClassId]/index.tsx
  src/pages/Classes/components/ExamForm.tsx
  src/pages/Classes/components/MediaContents.tsx
  src/pages/Classes/components/SubClassFileItem.tsx
  src/pages/Classes/hooks/useFileHandler.ts
  src/pages/Homework/hooks/useHomeworkForm.ts
  src/pages/Survey/hooks/useSurveyForm.ts
Labels: bug, fix

#209 refactor: 모달 및 UI 개선
  src/components/Backdrop.tsx
  src/components/ClassLayout/SubClassNavigationCard.tsx
  src/components/Header/AuthModal/Register.tsx
  src/components/Header/AuthModal/index.tsx
  src/components/Modal/ModalHeader.tsx
  src/components/Modal/index.tsx
  src/components/Pagination.tsx
  src/pages/Classes/components/ClassList.tsx
  src/pages/Community/components/MoreButton.tsx
  src/pages/Community/components/PostFormModal.tsx
  src/pages/Contact/components/ContactModal.tsx
  src/pages/Home/components/Hero.tsx
  src/pages/My/components/EditModal.tsx
  src/styles/global.css
Labels: feature, refactor, fix

#210 refactor: 액세스 토큰 관리 방식 수정
  src/hooks/auth/useLoginForm.ts
  src/hooks/auth/useLogout.ts
  src/hooks/homework/useGetHomework.ts
  src/hooks/survey/useGetSurvey.ts
  src/libs/api.ts
  src/pages/Community/hooks/useGetPost.ts
  src/stores/authSlice.ts
Labels: refactor
