Repository team-abcdedu/abcdedu-frontend, pull requests merged in 2024-10, with the labels that each got.

#213 refactor: 번들 사이즈 최적화
  .gitignore
  vite.config.ts
Labels: refactor

#214 fix: 사이드바 css, 버튼 수정
  src/components/Header/HeaderButtons.tsx
  src/components/Header/MobileNav.tsx
  src/components/Header/MobileSidebar.tsx
Labels: refactor, fix

#217 fix: 토큰 만료 시 로직 다시 추가
  src/libs/api.ts
Labels: bug, fix

#218 feat: robots.txt, sitemap 추가
  public/robots.txt
  public/sitemap.xml
  src/components/ClassLayout/SubClassNavigationCard.tsx
Labels: feature

#219 feat: sentry 모니터링 구축 및 ErrorBoundary 적용
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/assets/icons/students.webp
  src/components/AdminLayout.tsx
  src/components/ErrorBoundary/AccessError.tsx
  src/components/ErrorBoundary/DefaultFallback.tsx
  src/components/ErrorBoundary/index.tsx
  src/components/Layout.tsx
  src/libs/api.ts
  src/libs/react-query.ts
  src/libs/sentry.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/common.ts
  src/mocks/handlers.ts
  src/pages/AboutUs/Gallery.tsx
  src/pages/Community/Board.tsx
  src/pages/Community/PostDetail.tsx
  src/pages/Community/components/Comments.tsx
  src/pages/Community/components/List.tsx
  src/pages/Community/components/Post.tsx
  src/pages/Home/index.tsx
  src/pages/Homework/components/HomeworkForm.tsx
  src/pages/Homework/index.tsx
  src/pages/Survey/components/SurveyForm.tsx
  src/pages/Survey/index.tsx
  src/routes/index.tsx
  vite.config.ts
Labels: feature, refactor, fix

#220 fix: sentry 설정 수정
  src/libs/sentry.ts
  src/main.tsx
  src/pages/Home/index.tsx
Labels: fix

#222 fix: 회사소개 경로 수정
  src/components/Header/HeaderNav.tsx
  src/components/Header/MobileNav.tsx
Labels: bug

#225 fix: sentry sourcemap project 수정 #191
  vite.config.ts
Labels: bug, fix

#224 fix: 과제, 설문 캐시 문제 수정
  src/pages/Homework/components/HomeworkForm.tsx
  src/pages/Homework/index.tsx
  src/pages/Survey/components/SurveyForm.tsx
  src/pages/Survey/index.tsx
Labels: bug

#227 test: 테스트 환경 구축 및 ci 추가
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/components/Portal.test.tsx
  src/utils/isEndWithConsonant.test.ts
  tsconfig.json
  vite.config.ts
  vitest.setup.ts
Labels: test, build

#230 fix: 댓글 목록 조회 로직 수정
  src/mocks/handlers.ts
  src/pages/Community/components/Comments.tsx
  src/pages/Community/components/Post.tsx
  src/pages/Community/hooks/useGetComments.ts
Labels: fix

#233 feat: 메인페이지 모션 추가
  src/hooks/useIntersectionObserver.ts
  src/pages/Community/hooks/usePostForm.ts
  src/pages/Home/components/AboutUs.tsx
  src/pages/Home/components/Achievements.tsx
  src/pages/Home/components/AnimatedCounter.tsx
  src/pages/Home/components/AnimatedSection.tsx
  src/pages/Home/components/Banner.tsx
  src/pages/Home/components/ContentInfo.tsx
  src/pages/Home/components/Curriculum.tsx
  src/pages/Home/components/Hero.tsx
  src/pages/Home/components/Message.tsx
  src/pages/Home/components/Reviews/ReivewCard.tsx
  src/pages/Home/components/Reviews/ReviewSlide.tsx
  src/pages/Home/components/Reviews/index.tsx
  src/pages/Home/constants/index.ts
  src/pages/Home/index.tsx
  src/pages/Home/types/index.ts
  tailwind.config.js
Labels: feature, fix

#235 feat: 회원 가입 학교, 학번 필드 추가
  src/components/Header/AuthModal/Register.tsx
  src/hooks/auth/useRegisterForm.ts
  src/services/auth.ts
  src/types/auth.ts
Labels: feature

#239 feat: 비밀번호 변경 구현
  src/mocks/common.ts
  src/pages/My/components/EditAccount.tsx
  src/pages/My/components/EditModal.tsx
  src/pages/My/components/PasswordModal.tsx
  src/pages/My/components/ProfileInfo.tsx
  src/pages/My/components/ProfileModal.tsx
  src/pages/My/hooks/useAccountForm.ts
  src/pages/My/hooks/usePasswordForm.ts
  src/pages/My/index.tsx
  src/pages/My/types/index.ts
  src/services/user.ts
Labels: feature, refactor

#241 feat: 유저 조회, 검색 추가
  src/components/AdminLayout.tsx
  src/mocks/handlers.ts
  src/mocks/user.ts
  src/pages/Admin/User/components/RoleUpdater.tsx
  src/pages/Admin/User/components/SearchBar.tsx
  src/pages/Admin/User/hooks/useGetUserList.ts
  src/pages/Admin/User/index.tsx
  src/pages/Admin/constants/index.ts
  src/pages/Admin/constants/user.ts
  src/pages/Admin/types/index.ts
  src/routes/AdminRoutes.tsx
  src/services/admin/user.ts
  src/types/user.ts
Labels: feature
