Repository team-abcdedu/abcdedu-frontend, pull requests merged in 2024-11, with the labels that each got.

#244 fix: 비밀번호 변경 모달 닫을 때 form 초기화하도록 수정
  src/pages/My/components/PasswordModal.tsx
  src/pages/My/hooks/usePasswordForm.ts
Labels: bug

#245 feat: 관리자 - 멤버 등업 추가
  src/libs/api.ts
  src/mocks/handlers.ts
  src/pages/Admin/User/components/RoleUpdater.tsx
  src/pages/Admin/User/components/SearchBar.tsx
  src/pages/Admin/User/hooks/useCheckbox.ts
  src/pages/Admin/User/hooks/useGetUserList.ts
  src/pages/Admin/User/index.tsx
  src/services/admin/user.ts
  src/types/user.ts
Labels: feature

#246 deploy: 24-11-01 운영 서버 배포
  src/components/AdminLayout.tsx
  src/libs/api.ts
  src/mocks/handlers.ts
  src/mocks/user.ts
  src/pages/Admin/User/components/RoleUpdater.tsx
  src/pages/Admin/User/components/SearchBar.tsx
  src/pages/Admin/User/hooks/useCheckbox.ts
  src/pages/Admin/User/hooks/useGetUserList.ts
  src/pages/Admin/User/index.tsx
  src/pages/Admin/constants/index.ts
  src/pages/Admin/constants/user.ts
  src/pages/Admin/types/index.ts
  src/pages/My/components/PasswordModal.tsx
  src/pages/My/hooks/usePasswordForm.ts
  src/routes/AdminRoutes.tsx
  src/services/admin/user.ts
  src/types/user.ts
Labels: deploy

#249 fix: 학생 클래스 파일 접근 오류 수정
  src/pages/Classes/[classId]/[subClassId]/index.tsx
Labels: bug

#250 deploy: 24-11-05 (hotfix)
  src/pages/Classes/[classId]/[subClassId]/index.tsx
Labels: bug, deploy

#247 feat: 회원가입 이메일 인증 추가
  src/components/Header/AuthModal/EmailVerification.tsx
  src/components/Header/AuthModal/Login.tsx
  src/components/Header/AuthModal/Register.tsx
  src/components/Header/AuthModal/index.tsx
  src/components/Header/HeaderButtons.tsx
  src/components/MessageModal.tsx
  src/components/Modal/index.tsx
  src/components/Timer.tsx
  src/hooks/auth/useEmailVerification.ts
  src/hooks/auth/useLoginForm.ts
  src/hooks/auth/useRegisterForm.ts
  src/pages/My/hooks/usePasswordForm.ts
  src/services/auth.ts
  src/stores/authSlice.ts
  src/stores/emailVerificationSlice.ts
  src/stores/index.ts
  src/types/auth.ts
  tailwind.config.js
Labels: feature, refactor

#251 feat: 비밀번호 재설정 구현
  src/components/Header/AuthModal/ResetPassword.tsx
  src/components/Header/AuthModal/index.tsx
  src/hooks/auth/useResetPassword.ts
  src/services/auth.ts
Labels: feature

#253 feat: 이메일 인증 중복 이메일 예외 처리 추가
  src/hooks/auth/useEmailVerification.ts
Labels: feature

#255 fix: 문의 조회 api url 수정
  src/services/contact.ts
Labels: fix

#252 deploy: 24-11-14 운영 서버 배포
  src/components/Header/AuthModal/EmailVerification.tsx
  src/components/Header/AuthModal/Login.tsx
  src/components/Header/AuthModal/Register.tsx
  src/components/Header/AuthModal/ResetPassword.tsx
  src/components/Header/AuthModal/index.tsx
  src/components/Header/HeaderButtons.tsx
  src/components/MessageModal.tsx
  src/components/Modal/index.tsx
  src/components/Timer.tsx
  src/hooks/auth/useEmailVerification.ts
  src/hooks/auth/useLoginForm.ts
  src/hooks/auth/useRegisterForm.ts
  src/hooks/auth/useResetPassword.ts
  src/pages/My/hooks/usePasswordForm.ts
  src/services/auth.ts
  src/services/contact.ts
  src/stores/authSlice.ts
  src/stores/emailVerificationSlice.ts
  src/stores/index.ts
  src/types/auth.ts
  tailwind.config.js
Labels: deploy

#257 feat: 자료실 추가
  src/constants/navItems.ts
  src/pages/Community/Board.tsx
  src/pages/Community/components/List.tsx
  src/pages/Community/constants/communityInfo.ts
  src/pages/Community/hooks/useGetPosts.ts
  src/pages/Community/hooks/usePostForm.ts
  src/pages/Community/hooks/usePostMutation.ts
  src/services/community.ts
Labels: feature

#258 deploy: 24-11-14 운영 서버 배포(2)
  src/constants/navItems.ts
  src/pages/Community/Board.tsx
  src/pages/Community/components/List.tsx
  src/pages/Community/constants/communityInfo.ts
  src/pages/Community/hooks/useGetPosts.ts
  src/pages/Community/hooks/usePostForm.ts
  src/pages/Community/hooks/usePostMutation.ts
  src/services/community.ts
Labels: deploy

#261 refactor: 클래스 페이지 로직 분리
  src/components/ClassLayout/SubClassNavigationCardGroup.tsx
  src/components/ClassLayout/index.tsx
  src/hooks/class/useClassDataByParams.ts
  src/hooks/class/useClassDataList.ts
  src/hooks/class/useGetClass.ts
  src/hooks/class/useGetSubClassFileList.ts
  src/hooks/class/useGetSubClassIdMap.ts
  src/hooks/class/useSubClassFileHandler.ts
  src/hooks/class/useSubClassFileInfoList.ts
  src/pages/Admin/Class/components/ClassTable.tsx
  src/pages/Admin/Class/components/FileItem.tsx
  src/pages/Admin/Class/components/FileItemDetails.tsx
  src/pages/Admin/Class/components/FileList.tsx
  src/pages/Classes/[classId]/[subClassId]/index.tsx
  src/pages/Classes/[classId]/index.tsx
  src/pages/Classes/components/ClassContent.tsx
  src/pages/Classes/components/ClassList.tsx
  src/pages/Classes/components/ClassOverview.tsx
  src/pages/Classes/components/ExamContent.tsx
  src/pages/Classes/components/SubClassFileItem.tsx
  src/pages/Classes/components/SubClassNavigationCardGrid.tsx
  src/pages/Classes/hooks/useFileHandler.ts
  src/pages/Classes/hooks/useGetPdfUrl.ts
  src/pages/Classes/index.tsx
  src/pages/Classes/types/index.ts
  src/routes/PublicRoutes.tsx
  src/types/class.ts
  src/utils/convertS3ToPdfUrl.ts
  src/utils/getFileExtension.ts
Labels: refactor

#262 fix: 댓글 목록 조회 로직 수정
  src/pages/Community/components/Comments.tsx
  src/pages/Community/components/Post.tsx
  src/pages/Community/hooks/useGetComments.ts
Labels: bug, fix

#263 test: 프로필 페이지 테스트 코드 작성
  .gitignore
  package-lock.json
  package.json
  src/__test__/customRender.tsx
  src/__test__/mockSelectFile.ts
  src/components/FormErrorMessage.tsx
  src/components/Portal.test.tsx
  src/components/Skeleton.tsx
  src/pages/My/components/PasswordModal.test.tsx
  src/pages/My/components/PasswordModal.tsx
  src/pages/My/components/ProfileInfo.tsx
  src/pages/My/components/ProfileModal.test.tsx
  src/pages/My/components/ProfileModal.tsx
  src/pages/My/hooks/usePasswordForm.ts
  src/pages/My/hooks/useProfileForm.ts
  src/pages/My/index.test.tsx
  src/pages/My/types/index.ts
  src/utils/isEndWithConsonant.test.ts
  vite.config.ts
Labels: test, refactor, fix

#265 feat: 회원 탈퇴 구현
  src/pages/My/Leave.tsx
  src/pages/My/components/LeaveModal.tsx
  src/pages/My/components/ProfileModal.tsx
  src/pages/My/hooks/useLeave.ts
  src/pages/My/index.test.tsx
  src/pages/My/index.tsx
  src/routes/PrivateRoutes.tsx
  src/services/auth.ts
Labels: feature, fix

#267 refactor: subLectureId -> subClassId 변수명 통일
  src/hooks/class/useClassDataByParams.ts
  src/hooks/class/useSubClassFileInfoList.ts
  src/pages/Admin/Class/components/FileItem.tsx
  src/pages/Admin/Class/components/FileList.tsx
  src/pages/Admin/Class/components/FileUpdateModal.tsx
  src/pages/Admin/Class/components/FileUploadModal.tsx
  src/pages/Admin/Class/components/SubClassCard.tsx
  src/pages/Admin/Class/hooks/useFileUpdateMutation.ts
  src/pages/Admin/Class/hooks/useFileUploadMutation.ts
  src/services/admin/class.ts
  src/services/class.ts
Labels: refactor
