Repository team-abcdedu/abcdedu-frontend, pull requests merged in 2024-08, with the labels that each got.

#2 feat: 프로젝트 초기 세팅
  .eslintrc.cjs
  .gitignore
  .husky/pre-commit
  .prettierrc.cjs
  README.md
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/components/.gitkeep
  src/hooks/.gitkeep
  src/libs/react-query.ts
  src/main.tsx
  src/pages/Home.tsx
  src/routes/AdminRoutes.tsx
  src/routes/PrivateRoutes.tsx
  src/routes/PublicRoutes.tsx
  src/routes/index.tsx
  src/stores/.gitkeep
  src/styles/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: feature

#6 docs: pr 템플릿 설명 주석처리
  .github/pull_request_template.md
Labels: documentation

#5 feat: tailwind 세팅, dropdown 추가
  package-lock.json
  package.json
  postcss.config.js
  src/components/Dropdown.tsx
  tailwind.config.js
Labels: feature

#12 feat: 테마 색상 추가
  tailwind.config.js
Labels: feature

#10 feat: Modal 컴포넌트 구현
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/Backdrop.tsx
  src/components/Modal/ModalActions.tsx
  src/components/Modal/ModalContent.tsx
  src/components/Modal/index.tsx
  src/components/Portal.tsx
  src/hooks/.gitkeep
  src/hooks/useModal.ts
  src/hooks/useScrollLock.ts
  src/styles/.gitkeep
  src/styles/global.css
  src/types/.gitkeep
  src/types/index.ts
  tailwind.config.js
  vite.config.ts
Labels: feature

#16 fix: Header 스타일 수정
  src/components/Dropdown.tsx
  src/components/Header/HeaderButtons.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Header/HeaderNav.tsx
  src/components/Header/MobileMenu.tsx
  src/components/Header/MobileNav.tsx
  src/components/Header/index.tsx
  src/components/Layout.tsx
  tailwind.config.js
Labels: bug

#17 feat: Head 컴포넌트 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/Head.tsx
  src/pages/Home.tsx
Labels: feature

#22 feat: 메인페이지 퍼블리싱 (1차)
  .eslintrc.cjs
  .gitignore
  package-lock.json
  package.json
  src/assets/envelope.svg
  src/components/Footer/FooterNav.tsx
  src/components/Layout.tsx
  src/pages/Home.tsx
  src/pages/Home/components/Classes.tsx
  src/pages/Home/components/ContentInfo.tsx
  src/pages/Home/components/Hero.tsx
  src/pages/Home/components/Inquiry.tsx
  src/pages/Home/components/Introduce.tsx
  src/pages/Home/components/Message.tsx
  src/pages/Home/components/Reviews.tsx
  src/pages/Home/constants/imageUrls.ts
  src/pages/Home/index.tsx
  src/styles/global.css
  src/vite-env.d.ts
  tailwind.config.js
  vite.config.ts
Labels: bug, feature

#23 feat: 회원가입 및 로그인 모달 구현
  src/components/Header/AuthModal/Login.tsx
  src/components/Header/AuthModal/Register.tsx
  src/components/Header/AuthModal/index.tsx
  src/components/Header/HeaderButtons.tsx
  src/components/Modal/index.tsx
  src/styles/global.css
  src/types/auth.ts
Labels: feature

#25 클래스 메인 페이지 퍼블리싱
  src/pages/Classes/components/ClassContents.tsx
  src/pages/Classes/components/ClassList.tsx
  src/pages/Classes/components/Hero.tsx
  src/pages/Classes/components/MediaContents.tsx
  src/pages/Classes/constants/classInfo.ts
  src/pages/Classes/constants/imgUrl.ts
  src/pages/Classes/index.tsx
  src/routes/PublicRoutes.tsx
  src/types/classTypes.ts
  tailwind.config.js
Labels: feature

#29 폰트 추가
  src/assets/icons/envelope.svg
  src/assets/icons/kakaotalk.svg
  src/assets/icons/naver band.png
  src/assets/icons/naver blog.jpg
  src/assets/icons/react.svg
  src/assets/naver blog.png
  src/constants/snsItems.tsx
  src/pages/Home/components/Inquiry.tsx
  src/styles/fonts.css
  src/styles/global.css
Labels: feature

#33 Header 디자인 수정(모바일 미완)
  src/assets/icons/logo.png
  src/assets/icons/menu.svg
  src/assets/icons/user-login.svg
  src/components/Dropdown.tsx
  src/components/Header/HeaderButtons.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Header/HeaderNav.tsx
  src/components/Header/MobileMenu.tsx
  src/components/Header/MobileNav.tsx
  src/components/Header/index.tsx
  src/components/Layout.tsx
  src/constants/navItems.ts
  tailwind.config.js
Labels: feature

#35 커뮤니티 메인페이지 퍼블리싱
  src/pages/Community/Board.tsx
  src/pages/Community/LevelUp.tsx
  src/pages/Community/Project.tsx
  src/pages/Community/Qna.tsx
  src/pages/Community/Submit.tsx
  src/pages/Community/components/Boards.tsx
  src/pages/Community/components/CommunityContents.tsx
  src/pages/Community/components/Hero.tsx
  src/pages/Community/constants/communityInfo.ts
  src/pages/Community/index.tsx
  src/routes/PublicRoutes.tsx
  src/types/CommunityTypes.ts
Labels: feature

#37 feat: 메인 페이지 변경된 UI 반영
  src/assets/icons/arrow-right-outline.svg
  src/assets/icons/badge-with-laurel.svg
  src/assets/icons/clock.png
  src/assets/icons/laurel-wreath.svg
  src/assets/icons/school.png
  src/assets/icons/students.png
  src/assets/icons/thumbs-up.svg
  src/assets/images/handshake.png
  src/assets/images/hero-img.svg
  src/assets/images/snu.png
  src/pages/Home/components/AboutUs.tsx
  src/pages/Home/components/Achievements.tsx
  src/pages/Home/components/Classes.tsx
  src/pages/Home/components/ContentInfo.tsx
  src/pages/Home/components/Curriculum.tsx
  src/pages/Home/components/Hero.tsx
  src/pages/Home/components/Inquiry.tsx
  src/pages/Home/components/Introduce.tsx
  src/pages/Home/components/Message.tsx
  src/pages/Home/components/Reviews.tsx
  src/pages/Home/constants/imageUrls.ts
  src/pages/Home/constants/index.ts
  src/pages/Home/index.tsx
  src/pages/Home/types/index.ts
  src/styles/global.css
  tailwind.config.js
Labels: feature

#42 fix: 모달 애니메이션 버그 수정
  src/components/Backdrop.tsx
  src/components/Modal/index.tsx
Labels: bug

#39 헤더 수정(모바일 완)
  src/components/Dropdown.tsx
  src/components/Header/HeaderButtons.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Header/MobileMenu.tsx
  src/components/Header/MobileNav.tsx
  src/components/Header/index.tsx
  src/constants/navItems.ts
Labels: feature

#43 feat: 마이페이지 퍼블리싱
  src/components/PrivateRoute.tsx
  src/pages/My/components/EditAccount.tsx
  src/pages/My/components/EditModal.tsx
  src/pages/My/components/EditProfile.tsx
  src/pages/My/index.tsx
  src/pages/My/types/index.ts
  src/routes/PrivateRoutes.tsx
  src/styles/global.css
Labels: feature

#46 feat: 회원가입, 로그인 유효성 검사 추가
  package-lock.json
  package.json
  src/components/Header/AuthModal/Login.tsx
  src/components/Header/AuthModal/Register.tsx
  src/hooks/auth/useLoginForm.ts
  src/hooks/auth/useRegisterForm.ts
  src/styles/global.css
Labels: feature

#49 feat: 회원가입 구현
  src/components/Header/AuthModal/Login.tsx
  src/components/Header/AuthModal/Register.tsx
  src/config/index.ts
  src/hooks/auth/useRegisterForm.ts
  src/libs/api.ts
  src/services/auth.ts
  src/types/auth.ts
  src/types/index.ts
Labels: feature

#47 feat: 커뮤니티 게시판 중 등업 게시판 퍼블리싱
  src/components/Layout.tsx
  src/mock/Comment.tsx
  src/mock/Community.tsx
  src/pages/Community/LevelUp.tsx
  src/pages/Community/PostDetail.tsx
  src/pages/Community/components/PostData.tsx
  src/pages/Community/components/SecretAlert.tsx
  src/pages/Community/components/WirtePostModal.tsx
  src/pages/Community/types/Comment.ts
  src/pages/Community/types/PostData.ts
  src/pages/Community/types/WriteModal.ts
  src/routes/PublicRoutes.tsx
  src/types/CommunityTypes.ts
Labels: feature

#48 클래스 - 시험 항목 퍼블리싱
  package-lock.json
  package.json
  src/assets/icons/check-to-slot.svg
  src/components/QuillEditor/index.tsx
  src/components/QuillEditor/modules.ts
  src/pages/Classes/[courseId]/[classCode]/index.tsx
  src/pages/Classes/components/ClassContent.tsx
  src/pages/Classes/components/ExamForm.tsx
  src/pages/Classes/constants/courseInfo.ts
  src/styles/global.css
  src/types/classTypes.ts
  src/utils/.gitkeep
  src/utils/base64ToFile.ts
Labels: feature

#56 build 에러 수정
  .gitignore
  src/components/QuillEditor/index.tsx
  src/pages/Community/components/CommunityContents.tsx
  src/pages/Community/components/WirtePostModal.tsx
Labels: bug
